### ISSUE TITLE
Замечания к лабораторной

### ISSUE THREAD

**Issue by rredbird66** [Rom1xa/pzrllab2#1]
1. Неправильный формат вывода ответа в восьмеричной системе счисления.
![изображение](https://github.com/Rom1xa/pzrllab2/assets/36138085/e7706aaf-39dc-4df2-bdb4-ee439a260ad1)
2. Лучше не используйте perror. Success выглядит странно. Если хотите писать в поток ошибок, то можете использовать, например fprintf(stderr, "Msg %d", arg).
![изображение](https://github.com/Rom1xa/pzrllab2/assets/36138085/daac67bb-84a6-4b48-9bff-9b8dc7a70330)

**Comment by Rom1xa** [comment]
Замечания исправлены, я сделал так как в примере было в восмеричной системе. Пример 5:
Ввод:
010 * 020
Вывод:
200 (128)
сделал так чтобы выводило 0200 (128)

**Comment by Rom1xa** [comment]
> 1. Неправильный формат вывода ответа в восьмеричной системе счисления.
>    ![изображение](https://private-user-images.githubusercontent.com/36138085/291008632-e7706aaf-39dc-4df2-bdb4-ee439a260ad1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODc0NzksIm5iZiI6MTcwMzA4NzE3OSwicGF0aCI6Ii8zNjEzODA4NS8yOTEwMDg2MzItZTc3MDZhYWYtMzlkYy00ZGYyLWJkYjQtZWU0MzlhMjYwYWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE1NDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNzIyOWRiN2UxZTUxNjU1OTdmNTQ1ZWNmYzUyMDk4Nzc3NDAxMjdjOTRkNzA0MDJlMWM5MTk1M2E5MGI5NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gx2s48UuHdd0FR5KjwidGQF45vc9MwYVrkpydnYF2JU)
> 2. Лучше не используйте perror. Success выглядит странно. Если хотите писать в поток ошибок, то можете использовать, например fprintf(stderr, "Msg %d", arg).
>    ![изображение](https://private-user-images.githubusercontent.com/36138085/291008699-daac67bb-84a6-4b48-9bff-9b8dc7a70330.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODc0NzksIm5iZiI6MTcwMzA4NzE3OSwicGF0aCI6Ii8zNjEzODA4NS8yOTEwMDg2OTktZGFhYzY3YmItODRhNi00YjQ4LTliZmYtOWI4ZGM3YTcwMzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE1NDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZTc1NDM3OWNiMWI2ZGFlMjY4MDA3YTVkMDBmM2ZlYTJjMzhiM2YzMmFmNmU2ZWIzNjlkOTMwNTM5YmZiODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FCgeNu3QTg7yvUiPAjxbZ3rWStK-mLzzeKMsibNXMBo)

Исправил работу.

**Comment by rredbird66** [comment]
Да, там в задании опечатка, к сожалению. Должно быть 0200 в примере.
Лабораторная работа 2 зачтена.
